name: sho_tests
description: ITクイズアプリ

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  firebase_core: "^1.4.0"
  cloud_firestore: "^2.4.0"
  firebase_auth: "^3.0.1"
  google_sign_in: "^4.5.1"
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
